### ISSUE TITLE
NPM modules can't be used on Windows

### ISSUE THREAD

**Issue by linkvt** [brunch/brunch#1009]
Hi,

I used brunch with node modules on Linux without any problems; it worked perfectly for me. A few hours ago I tried to setup a brunch project (latest version 1.8.5, node.js v0.12.7) on my Windows machine, but without success. After at least an hour of trying to get it work, I debugged the issue.

I think that deppack, which was added in PR #930, isn't cross-platform compatible. While debugging I noticed, that e.g. [these functions](https://github.com/yavorsky/deppack/blob/master/src/deppack.coffee#L47) received paths with two backslashes, but expected single forwardslashes.
In the PR I noticed, that the author said that deppack should just be used temporarily.

Will deppack be replaced very soon (because of its temporarily use)? Otherwise I would notify @yavorsky.

Regards

**Comment by paulmillr** [comment]
I've published the new ver of deppack. Check it one more time please.

**Comment by linkvt** [comment]
Thanks for the fast reaction, my app.js contains the dependencies now. However it's not completely fixed.

I got an "loaderPath.indexOf is not a function", because the loaderPath was a boolean instead of a string in at least one case. After [diffing](https://www.diffchecker.com/9m1xxyjr) the generated `app.js` files I noticed, that the [modulePath variable here](https://github.com/yavorsky/deppack/blob/master/src/deppack.coffee#L120) contains single backslashes. This caused the path `node_modules` to become `*linebreak*ode_modules` and so on. This was because the double backslashes were replaced [here](https://github.com/brunch/brunch/blob/master/src/fs_utils/source_file.coffee#L70) by single ones.
I still have no clue why the `require` function is called with a `loaderPath=true`, but this call didn't happen on my Linux machine. I think it might be related to the different paths.


The cause might be in the following lines: https://github.com/brunch/commonjs-require-definition/blob/master/require.js#L34
Furthermore the equality comparison inside of the indexOf looks unintended: https://github.com/brunch/commonjs-require-definition/blob/master/require.js#L20

**Comment by paulmillr** [comment]
Let's investigate that

**Comment by pierr** [comment]
Any news on that?

**Comment by linkvt** [comment]
@pierr I'm really busy with other projects til mid of october, so at least I didn't investigate that issue further.

**Comment by paulmillr** [comment]
Let's move to gh-1023.
